const PDFDocument = require('pdfkit');

/**
 * Generate attendance PDF report
 */
function generateAttendancePDF(res, reportData) {
    const doc = new PDFDocument({ margin: 50 });

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${reportData.filename || 'attendance-report.pdf'}`);

    doc.pipe(res);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text('ClassTrack', { align: 'center' });
    doc.fontSize(14).font('Helvetica').text('Attendance Management System', { align: 'center' });
    doc.moveDown(0.5);

    // College and Class Info
    doc.fontSize(16).font('Helvetica-Bold').text('I BCA – 2nd Semester', { align: 'center' });
    doc.moveDown(1);

    // Report Info Box
    doc.rect(50, doc.y, 500, 80).stroke();
    const infoY = doc.y + 10;
    doc.fontSize(10).font('Helvetica');

    doc.text(`Date: ${reportData.date || new Date().toLocaleDateString()}`, 60, infoY);
    doc.text(`Day: ${reportData.day || ''}`, 60, infoY + 15);
    doc.text(`Period: ${reportData.period || 'All'}`, 60, infoY + 30);
    doc.text(`Time: ${reportData.timeRange || ''}`, 60, infoY + 45);

    doc.text(`Subject: ${reportData.subject || 'All'}`, 300, infoY);
    doc.text(`Report Type: ${reportData.reportType || 'Attendance'}`, 300, infoY + 15);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 300, infoY + 30);

    doc.y = infoY + 80;
    doc.moveDown(1);

    // Summary Stats
    if (reportData.summary) {
        doc.fontSize(12).font('Helvetica-Bold').text('Summary', 50);
        doc.fontSize(10).font('Helvetica');
        doc.text(`Total Students: ${reportData.summary.total || 0}`);
        doc.text(`Present: ${reportData.summary.present || 0}`);
        doc.text(`Absent: ${reportData.summary.absent || 0}`);
        doc.text(`Attendance Rate: ${reportData.summary.rate || 0}%`);
        doc.moveDown(1);
    }

    // Attendance Table
    if (reportData.attendance && reportData.attendance.length > 0) {
        drawAttendanceTable(doc, reportData.attendance);
    } else {
        doc.fontSize(12).text('No attendance records found for the selected criteria.', { align: 'center' });
    }

    // Footer
    doc.fontSize(8).text(
        'Generated by ClassTrack Attendance Management System',
        50,
        doc.page.height - 50,
        { align: 'center' }
    );

    doc.end();
}

/**
 * Draw attendance table in PDF
 */
function drawAttendanceTable(doc, attendance) {
    const tableTop = doc.y;
    const tableLeft = 50;
    const colWidths = [60, 200, 80, 80, 80];
    const headers = ['Roll No', 'Name', 'Gender', 'Status', 'Time'];

    // Table header
    doc.fontSize(10).font('Helvetica-Bold');
    let xPos = tableLeft;

    // Header background
    doc.rect(tableLeft, tableTop, 500, 20).fill('#2563eb');
    doc.fillColor('white');

    headers.forEach((header, i) => {
        doc.text(header, xPos + 5, tableTop + 5, { width: colWidths[i] - 10 });
        xPos += colWidths[i];
    });

    // Table rows
    doc.fillColor('black').font('Helvetica');
    let rowY = tableTop + 25;

    attendance.forEach((record, index) => {
        // Alternate row colors
        if (index % 2 === 0) {
            doc.rect(tableLeft, rowY - 3, 500, 18).fill('#f3f4f6');
            doc.fillColor('black');
        }

        xPos = tableLeft;
        const rowData = [
            record.roll_no || '',
            record.name || '',
            record.gender || '',
            record.status ? record.status.toUpperCase() : '',
            record.marked_at ? new Date(record.marked_at).toLocaleTimeString() : ''
        ];

        rowData.forEach((data, i) => {
            // Color code status
            if (i === 3) {
                doc.fillColor(data === 'PRESENT' ? '#059669' : '#dc2626');
            }
            doc.text(data, xPos + 5, rowY, { width: colWidths[i] - 10 });
            doc.fillColor('black');
            xPos += colWidths[i];
        });

        rowY += 18;

        // Add new page if needed
        if (rowY > doc.page.height - 100) {
            doc.addPage();
            rowY = 50;
        }
    });

    // Table border
    doc.rect(tableLeft, tableTop, 500, rowY - tableTop).stroke();
}

/**
 * Generate daily summary PDF
 */
function generateDailySummaryPDF(res, data) {
    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=daily-summary-${data.date}.pdf`);

    doc.pipe(res);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text('ClassTrack - Daily Summary', { align: 'center' });
    doc.fontSize(14).font('Helvetica').text('I BCA – 2nd Semester', { align: 'center' });
    doc.moveDown(0.5);
    doc.text(`Date: ${data.date} (${data.day})`, { align: 'center' });
    doc.moveDown(1);

    // Period-wise summary
    if (data.periods && data.periods.length > 0) {
        data.periods.forEach(period => {
            doc.fontSize(12).font('Helvetica-Bold');
            doc.text(`Period ${period.period}: ${period.subject} (${period.timeRange})`);
            doc.fontSize(10).font('Helvetica');
            doc.text(`Present: ${period.present} | Absent: ${period.absent} | Rate: ${period.rate}%`);
            doc.moveDown(0.5);
        });
    }

    doc.end();
}

/**
 * Generate student-wise PDF report
 */
function generateStudentPDF(res, data) {
    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=student-report-${data.student.roll_no}.pdf`);

    doc.pipe(res);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text('ClassTrack - Student Report', { align: 'center' });
    doc.moveDown(1);

    // Student Info
    doc.fontSize(14).font('Helvetica-Bold').text('Student Information');
    doc.fontSize(12).font('Helvetica');
    doc.text(`Name: ${data.student.name}`);
    doc.text(`Roll No: ${data.student.roll_no}`);
    doc.text(`Gender: ${data.student.gender}`);
    doc.moveDown(1);

    // Overall Stats
    doc.fontSize(14).font('Helvetica-Bold').text('Attendance Summary');
    doc.fontSize(12).font('Helvetica');
    doc.text(`Total Classes: ${data.stats.total}`);
    doc.text(`Present: ${data.stats.present}`);
    doc.text(`Absent: ${data.stats.absent}`);
    doc.text(`Attendance Rate: ${data.stats.rate}%`);
    doc.moveDown(1);

    // Subject-wise breakdown
    if (data.subjectWise && data.subjectWise.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').text('Subject-wise Breakdown');
        doc.fontSize(10).font('Helvetica');

        data.subjectWise.forEach(sub => {
            doc.text(`${sub.subject}: ${sub.present}/${sub.total} (${sub.rate}%)`);
        });
    }

    doc.end();
}

module.exports = {
    generateAttendancePDF,
    generateDailySummaryPDF,
    generateStudentPDF
};
